### ISSUE TITLE
some times fire this error can you help me.?? 

### ISSUE THREAD

**Issue by vishalpatel1327** [Odoo-mobile/framework#106]
i am not use other libs.. just start with this odoo-rpc-v3 lib i am just authenticate afetr login success with database.

 FATAL EXCEPTION: IntentService[OdooRegisterService]
                                                                     Process: com.myapp.login, PID: 28744
                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                         at com.om.DeviceInfo.getToken(DeviceInfo.java:151)
                                                                         at com.om.OdooRegister.register(OdooRegister.java:122)
                                                                         at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:54)
                                                                         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.myapp.login-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at com.om.DeviceInfo.getToken(DeviceInfo.java:151) 
                                                                         at com.om.OdooRegister.register(OdooRegister.java:122) 
                                                                         at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:54) 
                                                                         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 8 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by dpr-odoo** [comment]
@vishalpatel1327 

Just add google play service to your build.gradle of application

```groovy
compile 'com.google.android.gms:play-services:8.3.0'
```

**Comment by vishalpatel1327** [comment]
You are owsome man,
i am facing this because of old play-service lib 
i am update 
'com.google.android.gms:play-services:8.3.0'
and its done..

Odoo-v3 too deep and owsome lib..
thanks a lot.

**Comment by dpr-odoo** [comment]
:+1:
