### ISSUE TITLE
Java null pointer issue

### ISSUE THREAD

**Issue by midhunmadhuk** [Odoo-mobile/framework#114]
I have used your code in documentation for syncing datas from project but it shows following error while syncing ..

01-20 14:08:27.609 1424-1424/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.odoo, PID: 1424
                                                 java.lang.NullPointerException
                                                     at com.odoo.core.utils.OControls.setVisible(OControls.java:45)
                                                     at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:89)
                                                     at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:31)
                                                     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
                                                     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
                                                     at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                     at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                     at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                     at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
                                                     at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
                                                     at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
                                                     at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
                                                     at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by dpr-odoo** [comment]
@midhunmadhuk 

Looks like you are changing visibility of control that not initiated (in file **Tasks.java** line **89**) that caused the `NullPoitnerException`

**Comment by midhunmadhuk** [comment]
@dpr-odoo 
Thanks for your support issue fixed.

**Comment by midhunmadhuk** [comment]
Also I have one doubt how to fetch a data with specific conditions, I mean with domain. For an example I want to fetch only sale order with confirmed state where we can apply this domain in android framework.
Thanks in advance

**Comment by dpr-odoo** [comment]
@midhunmadhuk 

You can specify your domain filter for record at sync level : http://goo.gl/VYpLwQ in **performDataSync** as done in crm application for phonecalls here https://goo.gl/uQ0Rqs

**Comment by midhunmadhuk** [comment]
@dpr-odoo 

Ok but if I am using same model but I have to see it as separate menu in mobile app. Separation is based on states in this case I have make 2 performDataSync??

**Comment by dpr-odoo** [comment]
@midhunmadhuk 

No you don't need to create separate *performDataSync* , You can perform sync operation in same **performDataSync** method. You have to just pass bundle parameter when you request manual sync by calling **requestSync** from your Activity or Fragment on which to perform based on state_id by passing bundle data as, https://goo.gl/xlYzVm

You get this parameter in **performDataSync** and provide your domain as per your parameters and perform sync on same model with different domain : https://goo.gl/yuEXw8 *(Note: Keep it in condition so when user perform sync from android account the sync perform well without any domain filter)*


You can separate your menu based on state (state_id) as passed in extra bundle : https://goo.gl/KyqMhT and create new menu with different state_id and load as requested from menu. https://goo.gl/wxzI3F

Hope this will help.

**Comment by midhunmadhuk** [comment]
Thanks for your support @dpr-odoo. Also I have one more issue I have created a new model and that records are listing in mobile app and form view also visible,without add edit mode. After adding edit option in form I got this error. For this I have added datas in setMode and onOptionsItemSelected function. also I added this edit save and cancel in xml file aslo, do I need to add these details anywhere else, what will be the issue? Thanks in advance.
01-27 02:20:54.115 17822-17822/com.odoo E/dalvikvm: Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
01-27 02:25:20.703 17822-17822/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 17822
                                                          java.lang.NullPointerException
                                                              at com.odoo.addons.subscriptions.SubscriptionDetails.setMode(SubscriptionDetails.java:104)
                                                              at com.odoo.addons.subscriptions.SubscriptionDetails.onCreateOptionsMenu(SubscriptionDetails.java:269)
                                                              at android.app.Activity.onCreatePanelMenu(Activity.java:2538)
                                                              at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:298)
                                                              at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                              at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
                                                              at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                              at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
                                                              at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:136)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by dpr-odoo** [comment]
@midhunmadhuk 

I think you missed to initialize your Spinner view in **SubscriptionDetails.java** at line **104**

**Comment by midhunmadhuk** [comment]
Actually I followed what you did for customerDetails.Like below
           mMenu.findItem(R.id.menu_subscription_edit).setVisible(!edit);
            mMenu.findItem(R.id.menu_subscription_save).setVisible(edit);
            mMenu.findItem(R.id.menu_subscription_cancel).setVisible(edit);
