### ISSUE TITLE
Java SecurityException issue.

### ISSUE THREAD

**Issue by sufidu** [Odoo-mobile/framework#115]
I have downloaded the latest code and run using android Studio and got bellow exception.

E/OdooConnector(32284): [1032] BasicNetwork.performRequest: Unexpected response code 404 for https://www.odoo.com/auth_oauth/oea?access_token=a38917d8fda643b2be702b7415f5184b&scope=userinfo&expires_in=3600.0&response_type=token&client_id=null&db=openerp

 FATAL EXCEPTION: AsyncTask #2
 Process: com.odoo, PID: 32284
 java.lang.RuntimeException: An error occurred while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 	at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.SecurityException: uid 10369 cannot explicitly add accounts of type: com.odoo.auth
 	at android.os.Parcel.readException(Parcel.java:1620)
 	at android.os.Parcel.readException(Parcel.java:1573)
 	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:890)
 	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:712)
 	at com.odoo.core.auth.OdooAccountManager.createAccount(OdooAccountManager.java:93)
 	at com.odoo.core.account.OdooLogin$AccountCreater.doInBackground(OdooLogin.java:434)
 	at com.odoo.core.account.OdooLogin$AccountCreater.doInBackground(OdooLogin.java:421)
 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 	... 4 more

**Comment by dpr-odoo** [comment]
@sufidu 

Are you deploying the framework on mobile device with other *Odoo Mobile app* installed from **PlayStore**? any of these https://goo.gl/wJ0ojV ?

If yes, Than you need to change account auth type from following locations with your application ID and type auth:

- From authenticator xml file:  https://goo.gl/6WZxTw 
- From OdooAccountManager.java class : https://goo.gl/F8f6Ew

*Why required to change auth type?* It uses **"com.odoo.auth"** authentication type but you are building app from your system using Android Studio, and PlayStore application are build at our system. So application UID is different and app not able to create android application account in device with your system uid. So, just change auth type and deploy it again.

**Comment by sufidu** [comment]
@dpr-odoo 

It works.

I changed only the authenticator file before, that's why it's not working.

 Thank you very much.
