### ISSUE TITLE
FATAL EXCEPTION: IntentService [OdooRegisterService] - pls

### ISSUE THREAD

**Issue by 74n3r** [Odoo-mobile/framework#158]
Process: com.example, PID: 8235
                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'int odoo.helper.OdooVersion.getVersionNumber()' on a null object reference
                                                               at odoo.wrapper.OdooWrapper.bindOdooSession(OdooWrapper.java:547)
                                                               at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:449)
                                                               at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:440)
                                                               at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:51)
                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)

so sorry sir @dpr-odoo  
have we any idea ?

**Comment by kasim1011** [comment]
Did you solve this issue yet? @74n3r

**Comment by 74n3r** [comment]
hi @kasim1011  .. Unfortunately i didnt solve .. still trying on this..

**Comment by kasim1011** [comment]
I guess you're getting these errors when you're trying login. right?
@74n3r

**Comment by 74n3r** [comment]
@kasim1011 yeap kasım  .. going on errors..  i wrote to sir @dpr-odoo  but also doesnt answer..
