### ISSUE TITLE
android.database.sqlite.SQLiteException: no such column

### ISSUE THREAD

**Issue by 74n3r** [Odoo-mobile/framework#169]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.odoo.addons.Risk.RiskassesmentDetails}: android.database.sqlite.SQLiteException: no such column: subject (code 1): , while compiling: SELECT create_date, id, name, subject, _is_dirty, _id, _write_date, write_date, _is_active FROM isg_risk_assesment WHERE (_is_active = 'true') AND (_id = ?)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                            Caused by: android.database.sqlite.SQLiteException: no such column: subject (code 1): , while compiling: SELECT create_date, id, name, subject, _is_dirty, _id, _write_date, write_date, _is_active FROM isg_risk_assesment WHERE (_is_active = 'true') AND (_id = ?)
                                                               at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                               at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                               at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                               at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                               at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                               at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                               at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                               at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                               at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
                                                               at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
                                                               at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:107)
                                                               at android.content.ContentProvider.query(ContentProvider.java:1017)
                                                               at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
                                                               at android.content.ContentResolver.query(ContentResolver.java:491)
                                                               at android.content.ContentResolver.query(ContentResolver.java:434)
                                                               at com.odoo.core.orm.OModel.select(OModel.java:652)
                                                               at com.odoo.core.orm.OModel.select(OModel.java:648)
                                                               at com.odoo.core.orm.OModel.browse(OModel.java:591)
                                                               at com.odoo.core.orm.OModel.browse(OModel.java:587)
                                                               at com.odoo.addons.Risk.RiskassesmentDetails.setupActionBar(RiskassesmentDetails.java:137)
                                                               at com.odoo.addons.Risk.RiskassesmentDetails.onCreate(RiskassesmentDetails.java:87)
                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

hi guys.. i had errors .. who has any idea .. ?

**Comment by sylwek845** [comment]
try to clean you local db (uninstall the app maybe ?) and check all the spellings in your OModel class.

**Comment by 74n3r** [comment]
@sylwek845  yeap i was it .. unistall .. clean project .. rebuilt.. etc. 

shall i  write all values in OModel class ? 

 OColumn konu = new OColumn("konu", OVarchar.class).setName("subject");

i wanna just test himself values .. its comes or not ..

**Comment by YPerezM** [comment]
Every time you add a new OColumn you have to uninstall the app or will have this message error

**Comment by sylwek845** [comment]
@74n3r if your list for this module is working and then when you click on one item it crashes due to db error(app cant find specific column, eg in Omodel class you named it konu but in your server konu value does not exist ) try to add one item to Omodel class (only one to test it eg. name only) and try again

**Comment by kasim1011** [comment]
@74n3r Every time you make changes in database (Model files e.g.). you've to upgrade the version of database. or you just need full uninstallation than re-installation of app.

**Comment by 74n3r** [comment]
@sylwek845 @YPerezM @kasim1011  thnx guys.. i will try
