### ISSUE TITLE
odoo.helper.OdooVersion.getVersionNumber() - null

### ISSUE THREAD

**Issue by sylwek845** [Odoo-mobile/framework#195]
Hi, I have following error when I try to sync my modules ( not always) 

E/AndroidRuntime: FATAL EXCEPTION: IntentService[OdooRegisterService]
                  Process: com.corepd, PID: 12742
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int odoo.helper.OdooVersion.getVersionNumber()' on a null object reference
                      at odoo.wrapper.OdooWrapper.bindOdooSession(OdooWrapper.java:547)
                      at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:449)
                      at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:440)
                      at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:51)
                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:224)
                      at android.os.HandlerThread.run(HandlerThread.java:61)

any ideas ?

**Comment by sylwek845** [comment]
@dpr-odoo update on this error, it only occur on mobile data (UK)

**Comment by dpr-odoo** [comment]
library merged with latest commits. Fixed
