### ISSUE TITLE
Random SQLiteException (no such column: login) when accessing mail chatter

### ISSUE THREAD

**Issue by warp10** [Odoo-mobile/framework#203]
From time to time, opening activities/fragments with an OForm bound to models with setHasMailChatter(true) causes crashes in the app due to a weird SQLite error (please find the log here below). Once the app resumes after the crash, the very same activity/fragment can be opened with no problems at all. This all happens quite randomly, apparently without a proper reason causing the crash.

Steps to reproduce:
1- from activity/fragment A, open an activity/fragment B containing an OForm whose model has setHasMailChatter(true)
2- the app crashes with a log similar to the one you find here below
3- the app restarts itself
4- from A, open B again
5- activity/fragment B opens correctly and the mail thread is perfectly loaded.

```
07-25 10:26:20.399 20950-20950/it.openforce E/SQLiteLog: (1) no such column: login
07-25 10:26:20.409 20950-20950/it.openforce E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: it.openforce, PID: 20950
                                                              android.database.sqlite.SQLiteException: no such column: login (code 1): , while compiling: SELECT create_date, id, login, name, _is_dirty, _id, _write_date, write_date, _is_active FROM mail_message WHERE (_is_active = 'true') AND (_id = ?)
                                                              #################################################################
                                                              Error Code : 1 (SQLITE_ERROR)
                                                              Caused By : SQL(query) error or missing database.
                                                                (no such column: login (code 1): , while compiling: SELECT create_date, id, login, name, _is_dirty, _id, _write_date, write_date, _is_active FROM mail_message WHERE (_is_active = 'true') AND (_id = ?))
                                                              #################################################################
                                                                  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
                                                                  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                                  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                  at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                  at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1471)
                                                                  at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
                                                                  at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
                                                                  at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:108)
                                                                  at android.content.ContentProvider.query(ContentProvider.java:1058)
                                                                  at android.content.ContentProvider$Transport.query(ContentProvider.java:245)
                                                                  at android.content.ContentResolver.query(ContentResolver.java:502)
                                                                  at android.content.ContentResolver.query(ContentResolver.java:445)
                                                                  at com.odoo.core.orm.OModel.select(OModel.java:651)
                                                                  at com.odoo.core.orm.OModel.select(OModel.java:647)
                                                                  at com.odoo.core.orm.OModel.browse(OModel.java:590)
                                                                  at com.odoo.core.orm.OModel.browse(OModel.java:586)
                                                                  at com.odoo.addons.projects.adapters.AdapterProjectTasksList.getView(AdapterProjectTasksList.java:54)
                                                                  at android.widget.AbsListView.obtainView(AbsListView.java:2937)
                                                                  at android.widget.ListView.measureHeightOfChildren(ListView.java:1305)
                                                                  at android.widget.ListView.onMeasure(ListView.java:1212)
                                                                  at android.view.View.measure(View.java:20214)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                  at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1111)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:631)
                                                                  at android.view.View.measure(View.java:20214)
                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1624)
                                                                  at android.view.View.measure(View.java:20214)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:669)
                                                                  at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:89)
                                                                  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1319)
                                                                  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:734)
                                                                  at android.view.View.measure(View.java:20214)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                  at android.view.View.measure(View.java:20214)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                  at android.view.View.measure(View.java:20214)
                                                                at android.view
```

**Comment by dpr-odoo** [comment]
Issue with ``BaseModelProvider`` and model ``Uri`` and will be fixed in #243 
Closing issue.
