### ISSUE TITLE
Login in Error

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#206]
hi guys:
 when i am syncing data , then i add another account, the app will not working.
this is error:
`08-09 16:00:19.944 6411-7756/com.odoo.sita:sync_actualpackaging E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
                                                                                  java.lang.NullPointerException
                                                                                      at odoo.helper.OdooSession.parseSessionInfo(OdooSession.java:39)
                                                                                      at odoo.wrapper.OdooWrapper.getSessionInfo(OdooWrapper.java:343)
                                                                                      at odoo.wrapper.OdooWrapper.connect(OdooWrapper.java:135)
                                                                                      at odoo.Odoo.createQuickInstance(Odoo.java:116)
                                                                                      at com.odoo.core.service.OSyncAdapter.createOdooInstance(OSyncAdapter.java:328)
                                                                                      at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:122)
                                                                                      at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)`

**Comment by dpr-odoo** [comment]
@mikedream89 
I think it's solved with latest commits. Closing issue.
