### ISSUE TITLE
updateOnServer  error

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#212]
hi guys:
 `08-31 00:22:53.910 32497-32497/com.elico E/RecyclerView: No adapter attached; skipping layout
08-31 00:22:54.032 32497-32497/com.elico E/RecyclerView: No adapter attached; skipping layout
08-31 00:23:00.608 32497-32606/com.elico E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                           Process: com.elico, PID: 32497
                                                           java.lang.RuntimeException: An error occured while executing doInBackground()
                                                               at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
                                                               at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:86)
                                                               at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:93)
                                                               at android.content.ContentProvider.query(ContentProvider.java:966)
                                                               at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
                                                               at android.content.ContentResolver.query(ContentResolver.java:478)
                                                               at android.content.ContentResolver.query(ContentResolver.java:422)
                                                               at com.odoo.core.orm.OModel.select(OModel.java:651)
                                                               at com.odoo.core.orm.OModel.select(OModel.java:647)
                                                               at com.odoo.core.orm.OModel.selectRowId(OModel.java:797)
                                                               at com.odoo.core.orm.ServerDataHelper.updateOnServer(ServerDataHelper.java:148)
                                                               at com.odoo.addons.elico.inventory.models.StockInventoryLine$3.doInBackground(StockInventoryLine.java:145)
                                                               at com.odoo.addons.elico.inventory.models.StockInventoryLine$3.doInBackground(StockInventoryLine.java:133)
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818)`

When no data on my device, i use updateOnServer , this is  error information.
I find, the updateOnServer will update device database `(mModel.selectRowId(id)).`

> public int updateOnServer(ORecordValues data, Integer id) {
>         mOdoo.updateRecord(mModel.getModelName(), data, id);
>         return mModel.selectRowId(id);
>     }

[updateOnServer(ORecordValues data, Integer id)](https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/orm/ServerDataHelper.java)

**Comment by dpr-odoo** [comment]
closing similar issue. will be fixed in #243
