### ISSUE TITLE
SessionExpiredException: Session expired

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#221]
hi guys:
Why session expired?

2016-09-13 08:54:23,735 9 INFO ? werkzeug: 192.168.1.12 - - [13/Sep/2016 08:54:23] "POST /web/dataset/search_read HTTP/1.1" 200 -
2016-09-13 08:54:28,423 9 ERROR ? openerp.addons.web.http.JSONRequest.dispatch: An error occured while handling a json request
Traceback (most recent call last):
  File "/opt/odoo/sources/odoo/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/odoo/sources/odoo/web/addons/web/controllers/main.py", line 1054, in search_read
    return self.do_search_read(req, model, fields, offset, limit, domain, sort)
  File "/opt/odoo/sources/odoo/web/addons/web/controllers/main.py", line 1074, in do_search_read
    Model = req.session.model(model)
  File "/opt/odoo/sources/odoo/web/addons/web/session.py", line 158, in model
    raise SessionExpiredException("Session expired")
SessionExpiredException: Session expired

**Comment by asa-odoo** [comment]
@mikedream89 
Try it by increasing RPC_REQUEST_TIME_OUT.
May it helps to solve your issue.

**Comment by dpr-odoo** [comment]
@mikedream89 some of the fix done in framework. Can you use updated source.
