### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by FlowerMe1** [Odoo-mobile/framework#223]
I can't Login, it gives me this exception:
 FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 28928
                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                              at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1157)
                                                              at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5930)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by FlowerMe1** [comment]
Do anyone has suggestion about how to solve this issue

**Comment by r-mckay** [comment]
Hello,

from what I understand, this exception is thrown from the odoo-rpc-v3.aar, so it won't be easy to interact with it directly.

Maybe that you could enable Odoo's debug mode to get more logs, if it's not already the case. It will hopefully help you to understand what the problem is.

To achieve that, you can for example write something like:
`if (BuildConfig.DEBUG) {
            Odoo.DEBUG = true;
        }`
in the App.java's onCreate method.

I hope it will help, good luck.

**Comment by dpr-odoo** [comment]
@FlowerMe1 some of the fix done in latest commit. Can you check with updated source
