### ISSUE TITLE
Crash app when create a new customer with photo in the example app

### ISSUE THREAD

**Issue by robert2206** [Odoo-mobile/framework#228]
Steps to produce:
1. Go to customers and create new one
2. Take a picture to attach to customer data
3. Save and crash app

E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.eiru.odoo, PID: 6468
                                                             java.lang.IllegalStateException: Couldn't read row 0, col 18 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                 at android.database.CursorWindow.nativeGetString(Native Method)
                                                                 at android.database.CursorWindow.getString(CursorWindow.java:451)
                                                                 at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                                 at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                                 at com.odoo.core.support.list.OCursorListAdapter.notifyDataSetChanged(OCursorListAdapter.java:196)
                                                                 at android.widget.CursorAdapter.swapCursor(CursorAdapter.java:381)
                                                                 at android.widget.CursorAdapter.changeCursor(CursorAdapter.java:349)
                                                                 at com.odoo.addons.customers.Customers.onLoadFinished(Customers.java:148)
                                                                 at com.odoo.addons.customers.Customers.onLoadFinished(Customers.java:58)
                                                                 at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:479)
                                                                 at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:447)
                                                                 at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                                 at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                                 at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                                 at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
                                                                 at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
                                                                 at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
                                                                 at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
                                                                 at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by dpr-odoo** [comment]
@robert2206 
I think this crash due to large size of picture taken by camera and cursor not able to handle it and cursor  initialize fail.

**Comment by dpr-odoo** [comment]
@robert2206 fixed.
