### ISSUE TITLE
Login Page Error after completing selft-hosted URL

### ISSUE THREAD

**Issue by doniwahyu** [Odoo-mobile/framework#230]
Hi,

When i tried to login, i got this error : 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.odool, PID: 29100
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1157)
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
                      at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                      at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

Thanks,

**Comment by r-mckay** [comment]
Hi,
is it related to #223?

**Comment by doniwahyu** [comment]
yeah that's relate to me, but still got this error.  I tried My Odoo in play store to connect my server and success to login.

Anyone can help me, why session expired ? 
Thanks.

D/OdooLog: [1] OdooWrapper.newJSONPOSTRequest: POST DATA: {"jsonrpc":"2.0","method":"call","params":{},"id":2481}
D/OdooLog: [1] OdooWrapper.onResponse: RESPONSE:{"jsonrpc":"2.0","id":2481,"error":{"message":"Odoo Session Expired","code":100,"data":{"debug":"Traceback (most recent call last):\n  File \"\/opt\/odoo\/odoo\/http.py\", line 638, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"\/opt\/odoo\/odoo\/http.py\", line 675, in dispatch\n    result = self._call_function(**self.params)\n  File \"\/opt\/odoo\/odoo\/http.py\", line 332, in _call_function\n    return self.endpoint(*args, **kwargs)\n  File \"\/opt\/odoo\/odoo\/http.py\", line 933, in __call__\n    return self.method(*args, **kw)\n  File \"\/opt\/odoo\/odoo\/http.py\", line 504, in response_wrap\n    response = f(*args, **kw)\n  File \"\/opt\/odoo\/addons\/web\/controllers\/main.py\", line 702, in get_session_info\n    request.session.check_security()\n  File \"\/opt\/odoo\/odoo\/http.py\", line 1055, in check_security\n    raise SessionExpiredException(\"Session expired\")\nSessionExpiredException: Session expired\n","exception_type":"internal_error","message":"Session expired","name":"odoo.http.SessionExpiredException","arguments":["Session expired"]}}}
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.odool, PID: 30771
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1157)
                      at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
                      at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                      at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by doniwahyu** [comment]
I downgrade odoo to ver. 8 and working. :)
