### ISSUE TITLE
login for android error Odoo 10 version

### ISSUE THREAD

**Issue by purevsurento** [Odoo-mobile/framework#232]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.odoo, PID: 3019
                                                                java.lang.NullPointerException
                                                                    at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1157)
                                                                    at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
                                                                    at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                                    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by asa-odoo** [comment]
@purevsurento 
Odoo 10 is not supported
