### ISSUE TITLE
android odoo 9.0 version login error help

### ISSUE THREAD

**Issue by purevsurento** [Odoo-mobile/framework#233]
I can't Login, it gives me this exception:
FATAL EXCEPTION: main
Process: com.odoo, PID: 28928
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1157)
at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5930)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by dpr-odoo** [comment]
@purevsurento some of the fix done in latest commit. Can you check with updated source.

**Comment by dpr-odoo** [comment]
Related: https://github.com/Odoo-mobile/framework/issues/223
