### ISSUE TITLE
java.lang.NullPointerException: OSyncAdapter.java:92

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#237]
Hi, I've integrated [`Splunk Mint`](https://mint.splunk.com) error reporting service in my `framework` based  app. I'm keep getting force stop using following error.

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String odoo.helper.utils.gson.OdooResult.getString(java.lang.String)' on a null object reference`

here's the Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String odoo.helper.utils.gson.OdooResult.getString(java.lang.String)' on a null object reference
    at odoo.helper.OdooVersion.parseVersion(OdooVersion.java:70)
    at odoo.wrapper.OdooWrapper.getVersionInfo(OdooWrapper.java:309)
    at odoo.wrapper.OdooWrapper.connect(OdooWrapper.java:136)
    at odoo.Odoo.createQuickInstance(Odoo.java:116)
    at com.serpentcs.saltracker.core.service.OSyncAdapter.createOdooInstance(OSyncAdapter.java:92)
    at com.serpentcs.saltracker.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:148)
    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

![capture](https://cloud.githubusercontent.com/assets/7657803/19588546/126601aa-9784-11e6-82f6-8a83cb97939f.PNG)

**Comment by dpr-odoo** [comment]
@kasim1011 Can you check it with latest update.

**Comment by kasim1011** [comment]
yeah sure @dpr-odoo . I will let you know. Thanks.

**Comment by dpr-odoo** [comment]
Closing issue, If not solved please reopen it. Thanks.
