### ISSUE TITLE
java.lang.NullPointerException: OSyncAdapter.java:95

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#238]
Hi, I've integrated [`Splunk Mint`](https://mint.splunk.com) error reporting service in my `framework` based  app. I'm keep getting force stop using following error.

`java.lang.NullPointerException: Attempt to read from field 'odoo.helper.utils.gson.OdooResult odoo.helper.utils.gson.OdooResponse.result' on a null object reference`

here's the Stacktrace:

```
java.lang.NullPointerException: Attempt to read from field 'odoo.helper.utils.gson.OdooResult odoo.helper.utils.gson.OdooResponse.result' on a null object reference
    at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:448)
    at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:441)
    at com.serpentcs.saltracker.core.service.OSyncAdapter.createOdooInstance(OSyncAdapter.java:95)
    at com.serpentcs.saltracker.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:148)
    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

![capture1](https://cloud.githubusercontent.com/assets/7657803/19588833/f04efae8-9785-11e6-9103-2df45cc562d4.PNG)

**Comment by kalvian1060** [comment]
up,,,i m newbie

**Comment by dpr-odoo** [comment]
Looks like authentication error. https://github.com/Odoo-mobile/framework/issues/245 closing issue
