### ISSUE TITLE
java.lang.NullPointerException at OdooResult.java:50

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#240]
I've compile & run fresh framework app. It opens the `customer` fragment after successful `login`.
When I swipe down to `sync` data. application got crash with following error.

```
E/AndroidRuntime: FATAL EXCEPTION: IntentService[OdooRegisterService]
                  Process: com.odoo, PID: 31113
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                      at odoo.helper.utils.gson.OdooResult.getString(OdooResult.java:50)
                      at odoo.wrapper.OdooWrapper.parseUserObject(OdooWrapper.java:1157)
                      at odoo.wrapper.OdooWrapper.generateUserObject(OdooWrapper.java:1128)
                      at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:475)
                      at odoo.wrapper.OdooWrapper.authenticate(OdooWrapper.java:465)
                      at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:52)
                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.os.HandlerThread.run(HandlerThread.java:61)
```

Thanks in Advanced
@dpr-odoo and entire `odoo-mobile` community.

**Comment by dpr-odoo** [comment]
@kasim1011 Which Odoo version you are using ?

**Comment by kasim1011** [comment]
@dpr-odoo I'm using Odoo 8. Let me check with the latest update. I will let you know.

**Comment by dpr-odoo** [comment]
Closing issue. If not solved please reopen it. Thanks.

**Comment by thethtun** [comment]
I am using Odoo 10 with Mobile version 2.3.0.

03-25 15:11:19.795 12206-12206/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 12206
                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                              at com.odoo.core.rpc.helper.utils.gson.OdooResult.getString(OdooResult.java:50)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.bindOdooSession(OdooWrapper.java:509)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.access$400(OdooWrapper.java:72)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper$6.onResponse(OdooWrapper.java:457)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:993)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:72)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
