### ISSUE TITLE
Odoo server data read in use OdooResult result = db().getServerDataHelper().read() www.odoomobile.com call bug

### ISSUE THREAD

**Issue by purevsurento** [Odoo-mobile/framework#241]
Both Google Play Services and legacy GSF package are missing
10-24 17:05:52.263 26232-26350/ D/GCM: Failed to complete token refresh
                                                 java.io.IOException: MISSING_INSTANCEID_SERVICE
                                                     at com.google.android.gms.iid.zzc.zza(Unknown Source)
                                                     at com.google.android.gms.iid.zzc.zzb(Unknown Source)
                                                     at com.google.android.gms.iid.zzc.zza(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                     at com.om.DeviceInfo.getToken(DeviceInfo.java:152)
                                                     at com.om.OdooRegister.register(OdooRegister.java:122)
                                                     at com.om.OdooRegisterService.onHandleIntent(OdooRegisterService.java:57)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by dpr-odoo** [comment]
Which device you are using? Looks like your device does not have Google Play Services. If you are using Genymotion emulator please follow the tutorial https://inthecheesefactory.com/blog/how-to-install-google-services-on-genymotion/en

**Comment by purevsurento** [comment]
Odoo do to stop that server function called www.odoomobile.com dual attitude? it is likely www.odoomobile.com is a function that is a long time to be completed. Do you edit are accessible services www.odoomobile.com work? What can odoo-rpc-v3 Foundation source code?

**Comment by dpr-odoo** [comment]
Fixed in latest commits. Closing issue.

**Comment by dpr-odoo** [comment]
odoo-rpc-v3 source merged with framework https://github.com/Odoo-mobile/framework/commit/194303651a82cd5b0732f3529ea370e893ef8147
