### ISSUE TITLE
Cannot sync data from server

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#257]
hi @dpr-odoo 

I hava a table can not sync data from server.

this is my sync data on device's DB:

3716|true|false|2016-11-17 06:23:29|23106||||||||||ABC23084|||||||||||
3717|true|false|2016-11-17 06:23:29|23094||||||||||ABC23072|||||||||||
3718|true|false|2016-11-17 06:23:29|23093||||||||||ABC23071|||||||||||
3719|true|false|2016-11-17 06:23:29|23042||||||||||ABC23020|||||||||||
3720|true|false|2016-11-17 06:23:29|23052||||||||||ABC23030|||||||||||
3721|true|false|2016-11-17 06:23:29|23120||||||||||ABC23098|||||||||||
3722|true|false|2016-11-17 06:23:29|23067||||||||||ABC23045|||||||||||
3723|true|false|2016-11-17 06:23:29|23056||||||||||ABC23034|||||||||||
3724|true|false|2016-11-17 06:23:30|23055||||||||||ABC23033|||||||||||
3725|true|false|2016-11-17 06:23:30|23054||||||||||ABC23032|||||||||||

" |||||||||| "  this is sync data of fail.

How to find this is why?

**Comment by dpr-odoo** [comment]
@mikedream89 can you explain more. I'm not able to understand your issue.

Is these columns with **|** (pipe) separation?

**Comment by mikedream89** [comment]
@dpr-odoo 
3725|true|false|2016-11-17 06:23:30|23054||||||||||ABC23032|||||||||||

"||"  mean is null , data not sync to device's DB 

like:
columns:   _id      _is_active     _is_dirty             _write_date              id             name        A    B    C    D  
                3725 |        true       |     false    |  2016-11-17 06:23:30  |  23054  |  ABC23032  |    |      |     |      |

**Comment by dpr-odoo** [comment]
Is **A B C D** columns available on server ?

**Comment by mikedream89** [comment]
yes

**Comment by dpr-odoo** [comment]
Can you put android columns you have created for A B C D

**Comment by mikedream89** [comment]
A B C D columns available onserver, and i create A B C D columns on android, but these columns's data can not pull to android device's DB.

thanks

**Comment by mikedream89** [comment]
@dpr-odoo 
i know this is why:
table  TA has a column  TCA  manytoone  table TB .
when i only sync table TA , table TB only sync id and name columns .

How can i when i sync table TA , TB can be sync all columns?

**Comment by dpr-odoo** [comment]
@mikedream89 **TB** table has only *id* and *name* columns?

If yes, you can add other columns so it will automatically sync when **TA** table's **TCA** ManyToOne column sync.

If no and you want to sync all the data of table **TB** you can sync by adding chain sync in **TA**'s sync service as below:

In your **TA** table's Sync service

```java
public class TASyncService extends OSyncService implements ISyncFinishListener {
    
    private Context mContext;
    private OSyncService service;

    @Override
    public OSyncAdapter getSyncAdapter(OSyncService service, Context context) {
        mContext = context;
        this.service = service;
        // Your first table TB sync service adapter
        return new OSyncAdapter(context, TA.class, service, true);
    }

    @Override
    public void performDataSync(OSyncAdapter adapter, Bundle extras, OUser user) {

        // Check for syncing table name so you can specifiy any condition and domain
        if (adapter.getModel().getModelName().equals("ta")) {
            // Here, add callback for onSyncFinish so you can pass next sync adapter
            // It will implement ISyncFinishListener
            adapter.onSyncFinish(this); 
        }
    }

    @Override
    public OSyncAdapter performNextSync(OUser user, SyncResult syncResult) {

        // Pass you second table and it will perform full sync when TA sync finished
        return new OSyncAdapter(mContext, TB.class, service, true);
    }
}
```

**Comment by mikedream89** [comment]
@dpr-odoo 
11-18 10:29:58.694 3592-4097/com.odoo.sita:sync_qualitycontrolcontainer E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
                                                                                          java.lang.StackOverflowError
                                                                                              at java.util.WeakHashMap$Entry.<init>(WeakHashMap.java:71)
                                                                                              at java.util.WeakHashMap.put(WeakHashMap.java:630)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.finishAcquireConnectionLocked(SQLiteConnectionPool.java:911)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.tryAcquirePrimaryConnectionLocked(SQLiteConnectionPool.java:847)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:613)
                                                                                              at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                                                              at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                                                              at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586)
                                                                                              at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                              at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                              at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                              at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
                                                                                              at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
                                                                                              at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
                                                                                              at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:108)
                                                                                              at android.content.ContentProvider.query(ContentProvider.java:652)
                                                                                              at android.content.ContentProvider$Transport.query(ContentProvider.java:189)
                                                                                              at android.content.ContentResolver.query(ContentResolver.java:372)
                                                                                              at android.content.ContentResolver.query(ContentResolver.java:315)
                                                                                              at com.odoo.core.orm.OModel.select(OModel.java:652)
                                                                                              at com.odoo.core.orm.OModel.select(OModel.java:648)
                                                                                              at com.odoo.core.service.OSyncDataUtils.checkLocalUpdatedRecords(OSyncDataUtils.java:97)
                                                                                              at com.odoo.core.service.OSyncDataUtils.handleResult(OSyncDataUtils.java:72)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:206)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                              at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
                                                                                              at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:251)
                                                                                          	at com.odoo.core.service.OSyncAdapter.onPerformS

**Comment by mikedream89** [comment]
@dpr-odoo 

when **TA** finish to sync **TB**, and **TB** finish to sync **TC**, but **TC** not sync. this is my code.

```java
public class TASyncService extends OSyncService implements ISyncFinishListener {

    private Context mContext;
    private OSyncService service;

    @Override
    public OSyncAdapter getSyncAdapter(OSyncService service, Context context) {
        mContext = context;
        this.service = service;
        // Your first table TB sync service adapter
        return new OSyncAdapter(context, TA.class, service, true);
    }

    @Override
    public void performDataSync(OSyncAdapter adapter, Bundle extras, OUser user) {

        // Check for syncing table name so you can specifiy any condition and domain
        if (adapter.getModel().getModelName().equals("ta")) {
            // Here, add callback for onSyncFinish so you can pass next sync adapter
            // It will implement ISyncFinishListener
            adapter.onSyncFinish(this); 
        }
    }

    @Override
    public OSyncAdapter performNextSync(OUser user, SyncResult syncResult) {

        // Pass you second table and it will perform full sync when TA sync finished
        return new OSyncAdapter(mContext, TB.class, service, true);
    }
}
```

```java
public class TBSyncService extends OSyncService implements ISyncFinishListener {

    private Context mContext;
    private OSyncService service;

    @Override
    public OSyncAdapter getSyncAdapter(OSyncService service, Context context) {
        mContext = context;
        this.service = service;
        // Your first table TB sync service adapter
        return new OSyncAdapter(context, TB.class, service, true);
    }

    @Override
    public void performDataSync(OSyncAdapter adapter, Bundle extras, OUser user) {

        // Check for syncing table name so you can specifiy any condition and domain
        if (adapter.getModel().getModelName().equals("tb")) {
            // Here, add callback for onSyncFinish so you can pass next sync adapter
            // It will implement ISyncFinishListener
            adapter.onSyncFinish(this); 
        }
    }

    @Override
    public OSyncAdapter performNextSync(OUser user, SyncResult syncResult) {

        // Pass you second table and it will perform full sync when TB sync finished
        return new OSyncAdapter(mContext, TC.class, service, true);
    }
}
```

**Comment by dpr-odoo** [comment]
@mikedream89 
Okay, *Nesting of sync service not working*. Confirming it as bug.

**Comment by mikedream89** [comment]
@dpr-odoo 
Could you help me? thanks

**Comment by mikedream89** [comment]
11-28 18:06:33.881 1567-2854/com.odoo.sita E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
                                                             java.lang.OutOfMemoryError
                                                                 at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
                                                                 at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
                                                                 at java.lang.StringBuilder.append(StringBuilder.java:124)
                                                                 at org.json.JSONStringer.string(JSONStringer.java:344)
                                                                 at org.json.JSONStringer.value(JSONStringer.java:252)
                                                                 at org.json.JSONArray.writeTo(JSONArray.java:572)
                                                                 at org.json.JSONStringer.value(JSONStringer.java:233)
                                                                 at org.json.JSONObject.writeTo(JSONObject.java:667)
                                                                 at org.json.JSONStringer.value(JSONStringer.java:237)
                                                                 at org.json.JSONArray.writeTo(JSONArray.java:572)
                                                                 at org.json.JSONStringer.value(JSONStringer.java:233)
                                                                 at org.json.JSONObject.writeTo(JSONObject.java:667)
                                                                 at org.json.JSONStringer.value(JSONStringer.java:237)
                                                                 at org.json.JSONObject.writeTo(JSONObject.java:667)
                                                                 at org.json.JSONObject.toString(JSONObject.java:636)
                                                                 at com.odoo.core.rpc.wrapper.OdooWrapper.parseToResponse(OdooWrapper.java:1006)
                                                                 at com.odoo.core.rpc.wrapper.OdooWrapper.newJSONPOSTRequest(OdooWrapper.java:206)
                                                                 at com.odoo.core.rpc.wrapper.OdooWrapper.searchRead(OdooWrapper.java:600)
                                                                 at com.odoo.core.rpc.wrapper.OdooWrapper.searchRead(OdooWrapper.java:571)
                                                                 at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:182)
                                                                 at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)

**Comment by dpr-odoo** [comment]
Hello @mikedream89

I'm not able to reproduce this issue, and in your error it looks like **recursion happening** and it's go ``OutOfMemoryError``

Log the ``response`` object you are getting in ``OdooWrapper.java`` class at line ``1006``
https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/rpc/wrapper/OdooWrapper.java#L1006 so you can see whats you are getting from server and why code goes in recursion.
