### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference

### ISSUE THREAD

**Issue by kasim1011** [Odoo-mobile/framework#261]
I've done fresh install of Application. I'm getting `NullPointerException` at `setMatcher(BaseModelProvider.java:85) method`.

Here's the full log

	I/OdooActivity: Loading fragment: com.odoo.addons.customers.Customers
	I/OFragmentUtils: Fragment Loaded (com.odoo.addons.customers.Customers)
	E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
					  Process: com.odoo, PID: 31374
					  java.lang.RuntimeException: An error occurred while executing doInBackground()
						  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:153)
						  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
						  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
						  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
						  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
						  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
						  at java.lang.Thread.run(Thread.java:818)
					   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
						  at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
						  at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
						  at android.content.ContentProvider.query(ContentProvider.java:1017)
						  at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
						  at android.content.ContentResolver.query(ContentResolver.java:491)
						  at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:29)
						  at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
						  at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
						  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
						  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
						  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
						  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
						  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
						  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:133)
						  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
						  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
						  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
						  at java.lang.Thread.run(Thread.java:818) 

**Update**

I'm putting entire log from `LoginActivity` **login** button pressed to Application Force Stop. Hope It might Help. **Note:** I've **instant run** enabled in my Android studio.

	I/OdooAccountManager: Demo User Logged in successfully
	I/OSyncAdapter: User        : demo[adyen_8]
	I/OSyncAdapter: Model       : res.company
	I/OSyncAdapter: Database    : OdooSQLite_demo_adyen_8.db
	I/OSyncAdapter: Odoo Version: 8.0
	V/OSyncAdapter: Sync for (res.company) Started at 2016-11-20 23:42:41
	V/OSyncAdapter: Processing 1 records
	I/OSQLite: creating database.
	E/SQLiteLog: (1) no such table: res_company
	W/System.err: android.database.sqlite.SQLiteException: no such table: res_company (code 1): , while compiling: SELECT count(*) FROM res_company WHERE id = ?
	W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
	W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
	W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	W/System.err:     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
	W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
	W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
	W/System.err:     at com.odoo.core.orm.OModel.count(OModel.java:905)
	W/System.err:     at com.odoo.core.orm.OModel.hasServerRecord(OModel.java:804)
	W/System.err:     at com.odoo.core.service.OSyncDataUtils.checkLocalUpdatedRecords(OSyncDataUtils.java:86)
	W/System.err:     at com.odoo.core.service.OSyncDataUtils.handleResult(OSyncDataUtils.java:72)
	W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:201)
	W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
	W/System.err:     at com.odoo.core.orm.OModel.quickCreateRecord(OModel.java:1113)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:380)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:358)
	W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
	W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	W/System.err:     at java.lang.Thread.run(Thread.java:818)
	I/OSyncDataUtils: 0 records affected
	W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
	W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
	W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
	W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:1017)
	W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
	W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:491)
	W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:434)
	W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:641)
	W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:637)
	W/System.err:     at com.odoo.core.service.OSyncAdapter.removeRecordOnServer(OSyncAdapter.java:451)
	W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:218)
	W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)
	W/System.err:     at com.odoo.core.orm.OModel.quickCreateRecord(OModel.java:1113)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:380)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:358)
	W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
	W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	W/System.err:     at java.lang.Thread.run(Thread.java:818)
	W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
	W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
	W/System.err:     at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
	W/System.err:     at android.content.ContentProvider.query(ContentProvider.java:1017)
	W/System.err:     at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
	W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:491)
	W/System.err:     at android.content.ContentResolver.query(ContentResolver.java:434)
	W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:641)
	W/System.err:     at com.odoo.core.orm.OModel.select(OModel.java:637)
	W/System.err:     at com.odoo.core.orm.OModel.browse(OModel.java:588)
	W/System.err:     at com.odoo.core.orm.OModel.quickCreateRecord(OModel.java:1114)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:380)
	W/System.err:     at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:358)
	W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
	W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	W/System.err:     at java.lang.Thread.run(Thread.java:818)
	I/OdooActivity: OdooActivity->onCreate
	I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
	I/OdooActivity: Loading fragment: com.odoo.addons.customers.Customers
	I/OFragmentUtils: Fragment Loaded (com.odoo.addons.customers.Customers)
	E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
					  Process: com.odoo, PID: 10163
					  java.lang.RuntimeException: An error occurred while executing doInBackground()
						  at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:153)
						  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
						  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
						  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
						  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
						  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
						  at java.lang.Thread.run(Thread.java:818)
					   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.odoo.core.orm.OModel.getModelName()' on a null object reference
						  at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
						  at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
						  at android.content.ContentProvider.query(ContentProvider.java:1017)
						  at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
						  at android.content.ContentResolver.query(ContentResolver.java:491)
						  at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:29)
						  at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
						  at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
						  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
						  at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
						  at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
						  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
						  at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
						  at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:133)
						  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
						  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
						  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
						  at java.lang.Thread.run(Thread.java:818) 
	I/Process: Sending signal. PID: 10163 SIG: 9

**Comment by r-mckay** [comment]
Hello,
are you sure that all your models have correctly been registered by the makeReady method?
We encountered a similar issue with #258

**Comment by kasim1011** [comment]
@r-mckay I've added full log into issue. Please have look.

**Comment by r-mckay** [comment]
We also had a no such table exception.
Try to disable Instant Run.
Make sure that makeReady is configured to gather all of your models (see the condition with "startWith").

**Comment by kasim1011** [comment]
@r-mckay 
Thanks a lot. By disabling **instant run** Application is working fine

**Comment by r-mckay** [comment]
@kasim1011 glad it helped!

**Comment by bitsnaps** [comment]
> We also had a no such table exception.
> Try to disable Instant Run.
> Make sure that makeReady is configured to gather all of your models (see the condition with "startWith").

The `makeReady` method doesn't work as expected, it's tries to load models from `com.android.tools.*`, it also uses [DexFile](https://developer.android.com/reference/dalvik/system/DexFile) class which deprecated as api v26.
I'm still having this issue even with `instantRun` is disabled.

**Comment by bitsnaps** [comment]
> I'm still having this issue even with `instantRun` is disabled.

I just fixed this issue by disabling Instant Run not only from manifest file, but entirely from [Android Studio's option](https://stackoverflow.com/questions/46999669/how-to-disable-instant-run-for-android-studio-3-0).
