### ISSUE TITLE
Crashing on Login 

### ISSUE THREAD

**Issue by aj019** [Odoo-mobile/framework#308]
`02-13 15:20:57.513 8018-8187/com.odoo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
                                                        Process: com.odoo, PID: 8018
                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                            at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                            at java.lang.Thread.run(Thread.java:841)
                                                         Caused by: java.lang.SecurityException: caller uid 10097 is different than the authenticator's uid
                                                            at android.os.Parcel.readException(Parcel.java:1465)
                                                            at android.os.Parcel.readException(Parcel.java:1419)
                                                            at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:719)
                                                            at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:612)
                                                            at com.odoo.core.auth.OdooAccountManager.createAccount(OdooAccountManager.java:102)
                                                            at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:372)
                                                            at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:359)
                                                            at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                            at java.lang.Thread.run(Thread.java:841) 
`

**Comment by adam-nadar** [comment]
@aj019 is there any other application installed in target device developed on odoo mobile framework?
https://github.com/Odoo-mobile/framework/issues/303

**Comment by adam-nadar** [comment]
[https://github.com/Odoo-mobile/framework/issues/303](url)

**Comment by aj019** [comment]
@adam-nadar 
I have tested the application on my mobile phone as well as on a virtual device. If i enter the wrong credentials then the application redirects me to the login screen which is fine but when i enter the correct details then it shows Redirecting.. and after loading the home screen it crashes. So i am guessing that the application is able to connect to the server using the login credentials but is not able to fetch the necessary details from the server.

**Comment by asa-odoo** [comment]
@aj019 
if you have Instant Run enabled in Android Studio you need to disable it.
(https://developer.android.com/studio/run/index.html#disable-ir)

**Comment by jtampinco** [comment]
@aj019  How did you fix this?

**Comment by Tanererkan06** [comment]
@jtampinco https://developer.android.com/studio/run/index.html#disable-ir

**Comment by jtampinco** [comment]
@Tanererkan06 Sadly, it still didn't work. Any other suggestions?

**Comment by Tanererkan06** [comment]
@jtampinco  unfortunately .. but last friday was come to new update on Android Studio . Some bugs was fixed did u check it?
