### ISSUE TITLE
SqLite "No such column" error on Android 7.1

### ISSUE THREAD

**Issue by Tanererkan06** [Odoo-mobile/framework#311]
Hi Guys.. 

in my " inspection_model " own column's doesn't see .. 
 ( OColumn rapor_no = new OColumn("rapor_no", OVarchar.class).setName("rapor_no"); )

i was reinstall and re-buid :( Also change OModel's name 
 

E/SQLiteLog: (1) no such column:  " rapor_no "

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zodoo, PID: 3966
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zodoo/com.odoo.addons.inspection.inspectionDetails}: android.database.sqlite.SQLiteException: no such column: rapor_no (code 1): , while compiling: SELECT partner_id, create_date, id, name, _is_dirty, _write_date, _id, write_date, rapor_no, _is_active FROM isg_inspection WHERE (_is_active = 'true') AND (_id = ?)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.database.sqlite.SQLiteException: no such column: rapor_no (code 1): , while compiling: SELECT partner_id, create_date, id, name, _is_dirty, _write_date, _id, write_date, rapor_no, _is_active FROM isg_inspection WHERE (_is_active = 'true') AND (_id = ?)
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                      at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                      at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                      at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
                      at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
                      at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:107)
                      at android.content.ContentProvider.query(ContentProvider.java:1020)
                      at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
                      at android.content.ContentResolver.query(ContentResolver.java:532)
                      at android.content.ContentResolver.query(ContentResolver.java:474)
                      at com.odoo.core.orm.OModel.select(OModel.java:645)
                      at com.odoo.core.orm.OModel.select(OModel.java:641)
                      at com.odoo.core.orm.OModel.browse(OModel.java:584)
                      at com.odoo.core.orm.OModel.browse(OModel.java:580)
                      at com.odoo.addons.inspection.inspectionDetails.setupToolbar(inspectionDetails.java:133)
                      at com.odoo.addons.inspection.inspectionDetails.onCreate(inspectionDetails.java:89)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by mikedream89** [comment]
@Tanererkan06
 your db's tables are created in device's sqlite?  i also have this problem, my tables are not created.

**Comment by Tanererkan06** [comment]
yeap @mikedream89 ,  As like those i have problems.. 
in my opinion it's was so problems in ' Odoo Mobile 2.1 '. But we had solve with like x OMODEL class' name change , Project clean , re-build , re-install etc. For now hasn't....  

@asa-odoo what's needly thnx :(
