### ISSUE TITLE
Error generating SQLite database

### ISSUE THREAD

**Issue by yusdenis** [Odoo-mobile/framework#315]
Running the app for first time I had this error:

03-19 10:04:41.069 3383-3383/com.odoo E/SQLiteLog: (1) no such table: res_partner
03-19 10:04:41.077 3383-3383/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: com.odoo, PID: 3383
                                                        android.database.sqlite.SQLiteException: no such table: res_partner (code 1): , while compiling: SELECT count(*) FROM res_partner
                                                            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                                                            at com.odoo.core.orm.OModel.count(OModel.java:906)
                                                            at com.odoo.core.orm.OModel.isEmptyTable(OModel.java:607)
                                                            at com.odoo.addons.customers.Customers.onLoadFinished(Customers.java:169)
                                                            at com.odoo.addons.customers.Customers.onLoadFinished(Customers.java:57)
                                                            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
                                                            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
                                                            at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                            at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:252)
                                                            at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
                                                            at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
                                                            at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:154)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-19 10:04:51.967 3383-3398/com.odoo E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
03-19 10:04:51.967 3383-3398/com.odoo E/EGL_emulation: tid 3398: swapBuffers(487): error 0x300d (EGL_BAD_SURFACE)

**Comment by Tanererkan06** [comment]
@yusdenis  OMODEL class' name change , Project clean , re-build , re-install etc.  maybe it could be solve ..

**Comment by akshayjain1996** [comment]
I am getting a similar error. Did anyone get a way to fix this?

**Comment by MarioRamosEs** [comment]
Delete the app data and launch it again
