### ISSUE TITLE
SecurityException because of addAccountExplicitly

### ISSUE THREAD

**Issue by 1Androider** [Odoo-mobile/framework#318]
while executing this line `accountManager.addAccountExplicitly(account, String.valueOf(user.getPassword()), user.getAsBundle()))`
**getting error like**
Caused by: java.lang.SecurityException: uid 10328 cannot explicitly add accounts of type: com.odoo.auth
at android.os.Parcel.readException(Parcel.java:1683)
at android.os.Parcel.readException(Parcel.java:1636)
at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:995)
at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:733)
at com.odoo.core.auth.OdooAccountManager.createAccount(OdooAccountManager.java:111)
at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:441)
at com.odoo.core.account.OdooLogin$AccountCreator.doInBackground(OdooLogin.java:428)

Thanks in advance

**Comment by adam-nadar** [comment]
y don u try job schedulers ?

**Comment by kasim1011** [comment]
@1Androider 
Hi, When you get this type of security error, you'll require to ask for runtime permission for accessing Account. You can also avoid this by decreasing `targetSdkVersion` lower than `23` in your `build.gradle` file.

**Comment by flocsy** [comment]
@kasim1011 what permission that would be? What's the line to be added to AndroidManifest.xml?

**Comment by kasim1011** [comment]
@flocsy 
At [`authenticator.xml`](https://github.com/Odoo-mobile/framework/blob/master/app/src/main/res/xml/authenticator.xml)

	<account-authenticator xmlns:android="http://schemas.android.com/apk/res/android"
		android:accountType="com.odoo.auth"
		android:icon="@drawable/ic_odoo"
		android:label="@string/label_accounts_settings"
		android:smallIcon="@drawable/ic_odoo">

	</account-authenticator>

Change `accounttype` attribute to `your.package.name.auth`

At [`OdooAccountManager.java`](https://github.com/Odoo-mobile/framework/blob/master/app/src/main/java/com/odoo/core/auth/OdooAccountManager.java)

	public class OdooAccountManager {

		public static final String TAG = OdooAccountManager.class.getSimpleName();
		public static final String KEY_ACCOUNT_TYPE = "com.odoo.auth";
		public static final String KEY_USER_ACCOUNT_VERSION = "key_user_account_version";
		
		...


Change `KEY_ACCOUNT_TYPE` variable to `your.package.name.auth`.

Make above changes than tell me whether app is running properly or not?

**Comment by flocsy** [comment]
so it has nothing to do with permissions does it?

**Comment by kasim1011** [comment]
@flocsy 
The Error stack trace put by @1Androider has nothing to do with permissions.

Tell me, after doing above changes, app is working or not?
