### ISSUE TITLE
App Crash when trying to Login

### ISSUE THREAD

**Issue by sylwek845** [Odoo-mobile/framework#323]
My app is crashing when I'm trying to login 

> 05-31 00:13:27.230 27079-27079/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 27079
                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                              at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:1156)
                                                              at odoo.wrapper.OdooWrapper.onResponse(OdooWrapper.java:65)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:755)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:156)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

>

**Comment by pathob** [comment]
When I checkout the latest version of the Odoo Mobile Framework, OdooWrapper only has 1048 lines of code, but your defect occurs in line 1156. So either you have own customizations or you are not up to date. In the second case, please update the Framework and try again. Also, remember to turn off "Instant Run" when running the app in debug mode.

**Comment by mustafal** [comment]
**I had the same issue,
When i run the debug apk on my mobile it works fine, But when i make a release version of that apk the app crashes and the error is as following.**
`E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                          at com.serpentcs.ang_security.core.a.e.b.a(Unknown Source)
                                                          at com.serpentcs.ang_security.core.a.e.b.onResponse(Unknown Source)
                                                          at com.android.volley.toolbox.JsonRequest.deliverResponse(Unknown Source)
                                                          at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(Unknown Source)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-13 15:55:29.936 12229-12229/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.serpentcs.ang_security, PID: 12229
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                       at com.serpentcs.ang_security.core.a.e.b.a(Unknown Source)
                                                       at com.serpentcs.ang_security.core.a.e.b.onResponse(Unknown Source)
                                                       at com.android.volley.toolbox.JsonRequest.deliverResponse(Unknown Source)
                                                       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Please Guide Me What Should I do**
**Thanks**
