### ISSUE TITLE
app crashes using self-hosted url

### ISSUE THREAD

**Issue by ashish-greycube** [Odoo-mobile/framework#332]
07-11 21:11:26.811 17470-17897/com.odoo I/qtaguid: Untagging socket 55 failed errno=-22
07-11 21:11:26.811 17470-17897/com.odoo W/NetworkManagementSocketTagger: untagSocket(55) failed with errno -22
07-11 21:11:29.336 17470-17470/com.odoo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
07-11 21:11:29.336 17470-17470/com.odoo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
07-11 21:11:33.982 17470-17898/com.odoo I/qtaguid: Untagging socket 55 failed errno=-22
07-11 21:11:33.983 17470-17898/com.odoo W/NetworkManagementSocketTagger: untagSocket(55) failed with errno -22
07-11 21:11:34.004 17470-17470/com.odoo D/AndroidRuntime: Shutting down VM
07-11 21:11:34.005 17470-17470/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 17470
                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                              at com.odoo.core.rpc.helper.utils.gson.OdooResult.getString(OdooResult.java:50)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.bindOdooSession(OdooWrapper.java:509)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.access$400(OdooWrapper.java:72)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper$6.onResponse(OdooWrapper.java:457)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:993)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:72)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by naitikvithlani** [comment]
Hello,

Please double check your code in VM and real device as well, I am able to work with many of addons with is. (Find attached screen shot.)

![image](https://user-images.githubusercontent.com/6597323/31883342-34d2150e-b807-11e7-81b7-0751a1f69b38.png)

**Comment by ghost** [comment]
What device are you using for testing? What android version?

**Comment by naitikvithlani** [comment]
Android 7.0
