### ISSUE TITLE
new addon created chases when accesing in list view

### ISSUE THREAD

**Issue by robert2206** [Odoo-mobile/framework#333]
FATAL EXCEPTION: main
Process: com.odoo, PID: 18381
java.lang.NullPointerException
at com.odoo.core.utils.OControls.setGone(OControls.java:61)
at com.odoo.addons.products.ProductsTemplate$2.run(ProductsTemplate.java:119)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

**Comment by pathob** [comment]
Too few information...

**Comment by robert-gauto** [comment]
I've created a addon for product template following this tutorial http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/addons.html#creating-addon-with-odoo-mobile, then unistalling app and compile a new version from android studio, i launch app and i see new module created in sidebar but when i accessing chash app.

**Comment by robert-gauto** [comment]
I debug my app, and what I could see is that here is the problem, but I do not know why
![captura de pantalla de 2017-07-24 08-45-33](https://user-images.githubusercontent.com/13488157/28524195-76a1311a-704d-11e7-8081-3e19241f1f0f.png)

**Comment by pathob** [comment]
First of all, you are not using the latest version of the framework, which makes it harder to help you.

But basically, the method OControls.setGone(...) only contains the following two lines:

```java
View view = parent_view.findViewById(resource_id);
view.setVisibility(View.GONE);
```

So either the `parent_view` you are passing to this method is already `null` or more likely, this `parent_view` does not contain a view with the given `resource_id`.

**Comment by robert-gauto** [comment]
I clone the master branch from this repository https://github.com/Odoo-mobile/framework.git, this is not a latest version?, thanks for all @pathob

**Comment by pathob** [comment]
> So either the `parent_view` you are passing to this method is already `null` or more likely, this `parent_view` does not contain a view with the given `resource_id`.

You should concentrate on this... one of your views is null...

**Comment by euroblaze** [comment]
Did you fixed your problem? I have the same crash issue when i start the app after creating new addon

**Comment by naitikvithlani** [comment]
@euroblaze ,

I have added many addons in this, it works very good. (Find attached screen shots) 

![image](https://user-images.githubusercontent.com/6597323/31883235-d266739c-b806-11e7-9e3d-526e1c067b39.png)

**Comment by euroblaze** [comment]
Hello @naitikvithlani ,
Can you help me add too ?

**Comment by naitikvithlani** [comment]
Sure, Please send me an email about your requirement and the issue you
facing.

**Comment by haithem7** [comment]
can you please help me to make my application synch module entrepot!!
dahechhaithem7@gmail.com
