### ISSUE TITLE
helper.callMethod return and error

### ISSUE THREAD

**Issue by gfotal** [Odoo-mobile/framework#335]
java.lang.ClassCastException: java.lang.Boolean cannot be cast to org.json.JSONObject
     at com.odoo.addons.sales.models.SaleOrder.onPartnerIdChange(SaleOrder.java:93)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.odoo.core.orm.OModel.getOnChangeMethodValue(OModel.java:710)
     at odoo.controls.OForm$OnChangeBackground.doInBackground(OForm.java:359)
     at odoo.controls.OForm$OnChangeBackground.doInBackground(OForm.java:335)
     at android.os.AsyncTask$2.call(AsyncTask.java:288)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)

**Comment by truth6ker** [comment]
hello

I'm facing the same issue, did u manage to solve it?

thanks in advance
