### ISSUE TITLE
Random Volley parse error JSONException

### ISSUE THREAD

**Issue by AsKaeternam** [Odoo-mobile/framework#341]
Hello everyone,

I'm here because I've found an issue that randomly appears when trying to fetch data from Odoo with the framework.

This is the exception : 

`E/OdooLog: [229] OdooWrapper.newJSONPOSTRequest: 
                                                                                         java.util.concurrent.ExecutionException: com.android.volley.ParseError: org.json.JSONException: Unterminated object at character 261 of {"jsonrpc": "2.0", "id": 9085, "result": {"username": "xxx", "user_context": {"lang": "en_US", "tz": false, "uid": 1}, "uid": 1, "db": "xxx", "company_id": 1, "session_id": "bab2fa92fbcc7ae29eb32f176ea3b15d8b610bbd", "partner_id": 3}`

` at com.android.volley.toolbox.RequestFuture.doGet(RequestFuture.java:117)
                                                                                             at com.android.volley.toolbox.RequestFuture.get(RequestFuture.java:97)
                                                                                             at com.odoo.core.rpc.wrapper.OdooWrapper.newJSONPOSTRequest(OdooWrapper.java:209)
                                                                                             at com.odoo.core.rpc.wrapper.OdooWrapper.authenticate(OdooWrapper.java:452)
                                                                                             at com.odoo.core.rpc.wrapper.OdooWrapper.authenticate(OdooWrapper.java:417)
                                                                                             at com.odoo.core.service.OSyncAdapter.createOdooInstance(OSyncAdapter.java:304)
                                                                                             at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:118)`

Indeed, the json object returned by Odoo is not valid, because one '}' at the end is missing. It's look like a stream problem or something else.

This error doesn't only appear for a particular call but for every call performed by the framework. When I say randomly appears, it's because this exception doesn't appears everytime. Sometimes restarting the app will work well. This is a big issue because it can crash when a sync is performed.

Did you already be face this kind of issue ? Do you know how can we fix this ?

Thank you in advance,

Best regards

**Comment by naitikvithlani** [comment]
Hello @AsKaeternam ,

I am using this since very long time, i haven't facing this kind of issue.
Also, For sync issue i have implemented many of the odoo modules in this but seems working for me.(Find attached screen shot.)

![image](https://user-images.githubusercontent.com/6597323/31885606-b0879a78-b80e-11e7-89e7-e671f8d1b8b8.png)

**Comment by Martin78** [comment]
Hi AsKaeternam,

i have exactly the same problem! you have resolved it now? is this a odoo server problem or something with the odoo mobile framework?

BR
