### ISSUE TITLE
errors in the framework

### ISSUE THREAD

**Issue by leti2104** [Odoo-mobile/framework#348]
*how can I download the attachment that is placed in the messages
*It does NOT allow me to select the country and the state returns me to the registration screen

**Comment by naitikvithlani** [comment]
Hello @leti2104,
1) For download attachments from messages you just need to create URL with attachment id and attachment file name from the "**ir_attachment**" table from database.

2) I am able to select country and state (Find attached screen shots.)
![image](https://user-images.githubusercontent.com/6597323/31882554-c9a10968-b804-11e7-9bb8-a7d6d90f19f0.png)

For states, First of all you can't find the list of states, but when you search it once, you will find the searched state name in your list.(Find attached screen shot)

![image](https://user-images.githubusercontent.com/6597323/31882585-e2e21bf6-b804-11e7-897a-0705e3eff5d7.png)

Please let me know in case any details required for the same.

Thank You,
Best,

**Comment by leti2104** [comment]
hello @naitikvithlani 
Thank you very much for taking the time to answer my question, but I do not understand the method for downloading attachments from the app, I would greatly appreciate the more detailed in the subject

**Comment by naitikvithlani** [comment]
Hello @leti2104 ,

First you need to find attachment id of your attachment. (You will find in TABLE NAME "**mail_message_ir_attachment_rel**" in local database of application it's Many2Many field so it will store in another table)

Let's assume the your URL of attachment is "http://localhost:9010/web/content/590?download=1" , So for download the attachment you need to prepare URL for download file from URL like with given syntax : `<http://yourserver-address-with-port>/web/content/<attachment-id>?download=1` 

For double check you can check in your web browser.

Hope Will helpful for you.

Best Regards,

**Comment by leti2104** [comment]
Hello @naitikvithlani  
good morning in that part I already worked but now I do not know how to add the accounting module to the application and from what I see you already managed to make me you could provide the way that you did it if it is not much annoyance, I already read the documentation of odoo mobile but I can not understand since the documentation is different from the frame thanks and I expect a favorable response

**Comment by naitikvithlani** [comment]
Hello @leti2104 ,
Yes, You are right documentation is different then the code we have for this, In the current repository you will find the module of CRM, In the same way you need to add create code for accounting module.

For more details please send me the email for this.

Thank you.

**Comment by euroblaze** [comment]
Hello @naitikvithlani ,
Can you help me to with the problem u had creating new addon , i wrote on another issue . About listing the projects and the tasks of the user who is logged in .
Thank you

**Comment by naitikvithlani** [comment]
Sure, Please send me an email with your requirements and the issue you are
facing.

**Comment by euroblaze** [comment]
@naitikvithlani ,
I wrote you email on naitikvithlani@gmail.com , i guess this is your email .

**Comment by euroblaze** [comment]
Hello @leti2104 ,
Did you fix your problem that you had , i still have the same problem. My app crashes on start when i try to display my tasks and projects

**Comment by leti2104** [comment]
@euroblaze 
what is the error that is found when starting the application, if I would give more details so I can help you with pleasure I do

**Comment by euroblaze** [comment]
@leti2104 , This is copy of the logcat. If you can help please do. 

  Failed to find provider info for com.odoo.addons.projects.project_project
11-13 08:49:36.896 4341-5485/com.odoo:sync_tasks W/System.err: java.lang.IllegalArgumentException: Unknown URL content://com.odoo.addons.projects.project_project/project.project?key_model=project.project&key_username=m28%40euroblaze.de%5Bv9devblaze%5D
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at android.content.ContentResolver.insert(ContentResolver.java:1276)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.orm.OModel.insert(OModel.java:796)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.orm.OModel.insertOrUpdate(OModel.java:756)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.service.OSyncDataUtils.handleResult(OSyncDataUtils.java:208)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.service.OSyncDataUtils.handleResult(OSyncDataUtils.java:73)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.service.OSyncAdapter.syncData(OSyncAdapter.java:201)
11-13 08:49:36.897 4341-5485/com.odoo:sync_tasks W/System.err:     at com.odoo.core.service.OSyncAdapter.onPerformSync(OSyncAdapter.java:134)

**Comment by leti2104** [comment]
en alguna parte del codigo te confundiste y declaraste la clase mal, por
que la url es desconocida lo que indica que no encuentra en la ruta que le
pasaste los campos que declaraste
si gustas para hacer esto mas rapido te adjunto mi correo para que envies
por este medio mensaje y podamos estar en contacto de una manera mas rapida
y directa
leti76070@gmail.com

2017-11-13 1:56 GMT-06:00 Simplify-ERP® <notifications@github.com>:
