### ISSUE TITLE
Error when creating the Projet task from the documentation 

### ISSUE THREAD

**Issue by enerik** [Odoo-mobile/framework#354]
11-18 13:38:22.183 3643-3643/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: com.odoo, PID: 3643
                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
                                                            at com.odoo.core.utils.OControls.setGone(OControls.java:55)
                                                            at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:84)
                                                            at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:30)
                                                            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
                                                            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
                                                            at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                            at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:252)
                                                            at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
                                                            at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
                                                            at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:154)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by kasim1011** [comment]
@enerik 

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
at com.odoo.core.utils.OControls.setGone(OControls.java:55)
at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:84)
at com.odoo.addons.projects.Tasks.onLoadFinished(Tasks.java:30)`

Have you tried looking at line No. `84` in `Tasks.java`

**Comment by enerik** [comment]
yes i did , in fact i think  it was a problem of miswriting . 
I managed to get ride of that error and finally i got the projet task not crushing the app . 
Now i have another problem , The tasks wich i have in  server are not displayed on the app , 
It shows only the loading circle spinning and nothing . 
I have checked the code and i cant find any mistake .

**Comment by ghost** [comment]
@enerik 

Please, close the issue if your `project.task` sample is running fine.
