### ISSUE TITLE
Cannot perform this operation because the connection pool has been closed.

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#360]
Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                              at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                              at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
                                                              at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                              at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                              at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                              at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                              at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                              at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                              at android.content.ContentResolver.query(ContentResolver.java:510)
                                                              at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:33)
                                                              at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
                                                              at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
                                                              at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
                                                              at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
                                                              at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
                                                              at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by mikedream89** [comment]
Who can help me? Where is connection pool in framework?

**Comment by bimajatiwijaya** [comment]
How to reproduce error ?
I never get this error.
