### ISSUE TITLE
Odoo Android v2.3.0 Crashes after login

### ISSUE THREAD

**Issue by DonFeraRRi** [Odoo-mobile/framework#376]
**Affected version: 2.3.0**
**Reproduing: Just download the code and trying to run it. App launches well.
When I enter the login details, either the correct or false details, the app crashes.**

Log: 06-06 18:16:21.854 23155-23155/com.odoo I/art: Late-enabling -Xcheck:jni
06-06 18:16:21.886 23155-23162/com.odoo E/art: Failed sending reply to debugger: Broken pipe
06-06 18:16:21.889 23155-23162/com.odoo I/art: Debugger is no longer active
06-06 18:16:21.889 23155-23162/com.odoo I/art: Starting a blocking GC Instrumentation
06-06 18:16:21.918 23155-23155/com.odoo W/System: ClassLoader referenced unknown path: /data/app/com.odoo-1/lib/arm
06-06 18:16:22.050 23155-23155/com.odoo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-06 18:16:22.212 23155-23170/com.odoo I/Adreno: QUALCOMM build                   : 48a5bf5, I15255e4b4a
                                                  Build Date                       : 02/22/17
                                                  OpenGL ES Shader Compiler Version: XE031.09.00.03
                                                  Local Branch                     : 
                                                  Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.019
                                                  Remote Branch                    : NONE
                                                  Reconstruct Branch               : NOTHING
06-06 18:16:22.219 23155-23170/com.odoo I/OpenGLRenderer: Initialized EGL, version 1.4
06-06 18:16:22.219 23155-23170/com.odoo D/OpenGLRenderer: Swap behavior 1
06-06 18:16:26.870 23155-23155/com.odoo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
06-06 18:16:30.761 23155-23155/com.odoo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
06-06 18:16:32.077 23155-23155/com.odoo D/AndroidRuntime: Shutting down VM
06-06 18:16:32.078 23155-23155/com.odoo E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.odoo, PID: 23155
                                                          java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
                                                              at com.odoo.core.rpc.helper.OdooVersion.parseVersion(OdooVersion.java:74)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper$3.onResponse(OdooWrapper.java:275)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:993)
                                                              at com.odoo.core.rpc.wrapper.OdooWrapper.onResponse(OdooWrapper.java:72)
                                                              at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                              at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Any Help or link would be benefited.

**Comment by DonFeraRRi** [comment]
When I tried to open it through self hosted URL, I was able to login into my database. MY Question is, why it crashes when I enter my odoo login details?
