### ISSUE TITLE
Starting the application got this error in background

### ISSUE THREAD

**Issue by ketann** [Odoo-mobile/framework#74]
E/ActivityThread﹕ Service com.android.email.service.EmailBroadcastProcessorService has leaked ServiceConnection com.android.emailcommon.service.al@422bb708 that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.android.email.service.EmailBroadcastProcessorService has leaked ServiceConnection com.android.emailcommon.service.al@422bb708 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:979)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:873)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1690)
            at android.app.ContextImpl.bindService(ContextImpl.java:1673)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
            at com.android.emailcommon.service.aj.a(SourceFile:181)
            at com.android.emailcommon.service.aj.e(SourceFile:224)
            at com.android.email.service.n.c(SourceFile:164)
            at com.android.email.provider.b.a(SourceFile:189)
            at com.android.email.provider.b.a(SourceFile:133)
            at com.android.email.service.EmailBroadcastProcessorService.c(SourceFile:329)
            at com.android.email.service.EmailBroadcastProcessorService.onHandleIntent(SourceFile:1438)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dpr-odoo** [comment]
Are you using emulator for running app?

**Comment by ketann** [comment]
Sorry..........I am using real-device and i got error in real-device.

**Comment by dpr-odoo** [comment]
This error is not belong to Odoo Mobile App. Some of your email service is leaked.
