### ISSUE TITLE
I got this error when impliment GCM.

### ISSUE THREAD

**Issue by ketann** [Odoo-mobile/framework#75]
```
com.xxx E/BroadcastReceiver﹕ BroadcastReceiver trying to return result during a non-ordered broadcast
java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
        at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:783)
        at android.content.BroadcastReceiver.setResult(BroadcastReceiver.java:658)
        at com.google.android.gcm.GCMBroadcastReceiver.onReceive(GCMBroadcastReceiver.java:49)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2434)
        at android.app.ActivityThread.access$1700(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5086)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dpr-odoo** [comment]
@ketann  refer this issue on stackoverflow http://stackoverflow.com/a/23836204 will solve the error.

**Comment by svendhhh** [comment]
This isn't related to the SO question, as "setResult" is being called from "com.google.android.gcm.GCMBroadcastReceiver", so I'm thinking it's a bug in the android libraries?
