### ISSUE TITLE
Problem callMethod

### ISSUE THREAD

**Issue by sailing135** [Odoo-mobile/framework#78]
hello everybody!
With framework 3.0 : in framework-master\app\src\main\java\com\odoo\base\addons\res\ResUsers.java.
I implement method :

public static JSONArray get_child_partner(Context context, int user_id) {
        ResUsers users = new ResUsers(context, null);
        ServerDataHelper serverDataHelper = users.getServerDataHelper();
        OArguments loc = new OArguments();
        loc.add(user_id); 
        loc.add(new JSONObject()); 
        JSONArray jsonArray = (JSONArray) serverDataHelper.callMethod("get_child_partner", loc, null);
        return jsonArray;
    }

Then I was called it in framework-master\app\src\main\java\com\odoo\addons\customers\Customers.java

as: ResUsers.get_child_partner(getActivity(),user_id);

=>> crash

07-15 17:18:43.826  30338-30338/com.odoo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.odoo.core.orm.ServerDataHelper.callMethod(ServerDataHelper.java:123)
            at com.odoo.core.orm.ServerDataHelper.callMethod(ServerDataHelper.java:114)
            at com.odoo.core.orm.ServerDataHelper.callMethod(ServerDataHelper.java:105)
            at com.odoo.base.addons.res.ResUsers.get_child_partner(ResUsers.java:77)
            at com.odoo.addons.customers.Customers.onViewCreated(Customers.java:101)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
            at android.os.Handler.handleCallback(Handler.java:800)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)

please help me !!!

**Comment by tks-dp** [comment]
Possible null values can be 
context, user_id, users,  serverDataHelper, getActivity() 

You also needs to confirm that you are passing proper values with relevant format and in the sequence of the parameter defined in the function definition.

**Comment by sailing135** [comment]
Hi tks-dp,

I debug context, user_id, users,...Then I have seen all not null.
In ver2.0, I have also done so but not crash. Method callMethod only crashes on ver3.0.

please help me, thanks!

**Comment by tks-dp** [comment]
Try to call this method from ServerDataHelper.java

    public Object callMethod(String model, String method, OArguments args,
                             HashMap<String, Object> context, HashMap<String, Object> kwargs) {...}

check the values over here, and try to print the output of 
        OdooResult result = mOdoo.callMethod(model, method, args, kwargs, context);


may be you are getting any server side error ?? !! 

I haven't used ver3.0, but probably that can help you.

**Comment by sailing135** [comment]
Hi!
please,  can you help me demo callMethod with the lastest version to not crash?
thanks.

**Comment by tks-dp** [comment]
Try this! 

JSONArray jsonArray = (JSONArray) serverDataHelper.callMethod("res.users","get_child_partner", loc.getArray(), null, null);


Make sure that you passes the correct parameter with correct format of the values to server side tooo,...

**Comment by sailing135** [comment]
Hi,
Thanks for help me, but with loc.getArray() => error "Wrong 3rd argument type. Found: 'org.json.JSONArray', required: 'odoo.helper.OArguments'
I don't understand why with V.2 then library are: import odoo.OArguments; import odoo.ODomain;  but in V3 library are: import odoo.helper.OArguments; import odoo.helper.ODomain;
Any help please!!

**Comment by tks-dp** [comment]
```
With loc.getArray() => error "Wrong 3rd argument type. Found: 'org.json.JSONArray', required: 'odoo.helper.OArguments'
```

Try using only 'loc' instead of getting the Array using .getArray()

This is the basic concept of Android(or specifically JAVA) that the language is very strict to its data type, that means even though the Array and JSONArray are having the same concept of collection of item, their classes are different in Android.

```
I don't understand why with V.2 then library are: import odoo.OArguments; import odoo.ODomain; but in V3 library are: import odoo.helper.OArguments; import odoo.helper.ODomain;
Any help please!!
```

That is just because they have changed the package structure, for the classes we used from the Odoo-x.jar

so if you want to have used odoo lib v2 then you can use odoo.OArguments...
else if lib is v3,  you have to use odoo.helper.OArguments

Do not try to use v2 and v3 in the same project!!!!

**Comment by SELKHOUFAIRI** [comment]
Hi everyone,
I have a problem concerning groups in odoo mobile framework , i don't know how to get the group of the connected user
thank u in advance.

**Comment by dpr-odoo** [comment]
@sailing135 Just add **child_ids** column of type **OneToMany** in **ResPartner** model (i.e., already exist on server model res.partner). It will auto sync child partners if exists at synchronization time. 

You can browse each childs by **row.getO2MRecords("child_ids").browseEach()**
