### ISSUE TITLE
Connect database from website use Odoo to app Odoo mobile.

### ISSUE THREAD

**Issue by NguyenAnhTuyen** [Odoo-mobile/framework#95]
Hi everyone, I'm newbie android and Odoo mobile, I'm building a mobile application an e-commerce. I have addon using Odoo, I have an addon which shows information about name, price,....However, I have some problems:
- To create this addon, I have model ProductProduct with column same in web database. However it does not sync database between website and app mobile. It appearance problem:
- When I login with new account it not error, but my application exits.
- When I login with existed account, an error appears:
  10-21 22:52:04.169  29337-29470/com.odoo E/AndroidRuntime﹕ FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.odoo, PID: 29337
    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NullPointerException
            at com.odoo.core.orm.provider.BaseModelProvider.setMatcher(BaseModelProvider.java:85)
            at com.odoo.core.orm.provider.BaseModelProvider.query(BaseModelProvider.java:92)
            at android.content.ContentProvider.query(ContentProvider.java:904)
            at android.content.ContentProvider$Transport.query(ContentProvider.java:234)
            at android.content.ContentResolver.query(ContentResolver.java:462)
            at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:27)
            at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:56)
            at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:114)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
              at java.lang.Thread.run(Thread.java:841)

What are my problem and how can I solve them ? Thank so much for reading. 
P/s: My english is not good, I hope you understand what I my mean.

**Comment by Kelbethor** [comment]
I'm no expert but I think you could check your defined provider and service in the manifest xml file and also SyncAdapter file...  error here, is setMatcher is receiving null Uri argument so I think some information is missing or wrong for sync service

**Comment by dpr-odoo** [comment]
Consider this answer : https://github.com/Odoo-mobile/framework/issues/165#issuecomment-260563404
